In [1]:
import pandas as pd
df = pd.DataFrame([[2,5,5,8,7],[5,4,8,7,9],[5,4,7,5,2]],columns = ["a","b","c","d","e"])

In [2]:
df = pd.DataFrame([[2,5,5,8,7],[5,4,8,7,9],[5,4,7,5,2]],columns = ["a","b","c","d","e"])

In [3]:
df.columns

Index(['a', 'b', 'c', 'd', 'e'], dtype='str')

In [4]:
gut = pd.read_csv(r"C:\Users\aalgo\Downloads\archive_(4)\Amazon_Sale_Report.csv")

C:\Users\aalgo\AppData\Local\Temp\ipykernel_29136\3729815047.py:1: DtypeWarning: Columns (0: Unnamed: 22) have mixed types. Specify dtype option on import or set low_memory=False.
  gut = pd.read_csv(r"C:\Users\aalgo\Downloads\archive_(4)\Amazon_Sale_Report.csv")

In [5]:
gut.loc[gut['Amount'] > 700,['Category','currency','Amount']]

             Category currency   Amount
3       Western Dress      INR   753.33
5                 Set      INR   824.00
14                Set      INR   771.00
19                Set      INR   886.00
30      Western Dress      INR   791.00
...               ...      ...      ...
128964  Western Dress      INR   899.00
128966            Set      INR  1132.00
128968            Set      INR   824.00
128971            Set      INR   999.00
128973            Set      INR  1199.00

[45261 rows x 3 columns]

In [ ]:
gut[(gut['Amount'] > 700)]

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN
5,5,404-1490984-4578765,04-30-22,Shipped,Amazon,Amazon.in,Expedited,SET264,SET264-KR-NP-XL,Set,...,INR,824.00,GHAZIABAD,UTTAR PRADESH,201102.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
6,6,408-5748499-6859555,04-30-22,Shipped,Amazon,Amazon.in,Expedited,J0095,J0095-SET-L,Set,...,INR,653.00,CHANDIGARH,CHANDIGARH,160036.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
7,7,406-7807733-3785945,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3405,JNE3405-KR-S,kurta,...,INR,399.00,HYDERABAD,TELANGANA,500032.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
8,8,407-5443024-5233168,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,SET200,SET200-KR-NP-A-XXXL,Set,...,NaN,NaN,HYDERABAD,TELANGANA,500008.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
9,9,402-4393761-0311520,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3461,JNE3461-KR-XXL,kurta,...,INR,363.00,Chennai,TAMIL NADU,600041.0,IN,NaN,False,NaN,NaN

In [7]:
gut[(gut['Amount'] > 700) & (gut['Category']=='Set')]

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
5,5,404-1490984-4578765,04-30-22,Shipped,Amazon,Amazon.in,Expedited,SET264,SET264-KR-NP-XL,Set,...,INR,824.0,GHAZIABAD,UTTAR PRADESH,201102.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
14,14,408-1298370-1920302,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,J0351,J0351-SET-L,Set,...,INR,771.0,MUMBAI,MAHARASHTRA,400053.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
19,19,405-5957858-1051546,04-30-22,Shipped,Amazon,Amazon.in,Expedited,SET254,SET254-KR-NP-XS,Set,...,INR,886.0,BENGALURU,KARNATAKA,560017.0,IN,NaN,False,NaN,NaN
32,32,404-9632124-1107550,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,J0011,J0011-LCD-M,Set,...,INR,1233.0,VISAKHAPATNAM,ANDHRA PRADESH,530016.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
43,43,408-3478480-0881162,04-30-22,Shipped,Amazon,Amazon.in,Expedited,SET360,SET360-KR-NP-M,Set,...,INR,1126.0,LUCKNOW,UTTAR PRADESH,226017.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128957,128957,402-8261465-0622733,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0230,J0230-SKD-M,Set,...,INR,1349.0,RANCHI,JHARKHAND,834002.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128966,128966,406-9812666-2474761,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET224,SET224-KR-NP-XS,Set,...,INR,1132.0,CHENNAI 600042,TAMIL NADU,600042.0,IN,NaN,False,NaN,False
128968,128968,403-7059995-7618722,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET264,SET264-KR-NP-XL,Set,...,INR,824.0,Delhi,DELHI,110053.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128971,128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,...,INR,999.0,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128973,128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,...,INR,1199.0,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False

In [11]:
gut[gut['Category'].str.contains("set",case = False)]

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
5,5,404-1490984-4578765,04-30-22,Shipped,Amazon,Amazon.in,Expedited,SET264,SET264-KR-NP-XL,Set,...,INR,824.00,GHAZIABAD,UTTAR PRADESH,201102.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
6,6,408-5748499-6859555,04-30-22,Shipped,Amazon,Amazon.in,Expedited,J0095,J0095-SET-L,Set,...,INR,653.00,CHANDIGARH,CHANDIGARH,160036.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
8,8,407-5443024-5233168,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,SET200,SET200-KR-NP-A-XXXL,Set,...,NaN,NaN,HYDERABAD,TELANGANA,500008.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
13,13,408-7955685-3083534,04-30-22,Shipped,Amazon,Amazon.in,Expedited,SET182,SET182-KR-DH-XS,Set,...,INR,657.00,MUMBAI,MAHARASHTRA,400053.0,IN,NaN,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128968,128968,403-7059995-7618722,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET264,SET264-KR-NP-XL,Set,...,INR,824.00,Delhi,DELHI,110053.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128969,128969,404-3802633-7250760,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,SET044,SET044-KR-NP-M,Set,...,INR,612.00,MUMBAI,MAHARASHTRA,400017.0,IN,NaN,False,NaN,False
128971,128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,...,INR,999.00,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128973,128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,...,INR,1199.00,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128974,128974,408-7436540-8728312,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,...,INR,696.00,Raipur,CHHATTISGARH,492014.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False

In [20]:
gut[gut['Category'].str.contains("top",case=False)]

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.0,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN
47,47,408-9281152-6213100,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3744,JNE3744-TU-S,Top,...,INR,665.0,SECUNDERABAD,TELANGANA,500017.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
54,54,402-7944191-1869101,04-30-22,Shipped,Amazon,Amazon.in,Expedited,J0301,J0301-TP-L,Top,...,INR,493.0,BENGALURU,KARNATAKA,560076.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
67,67,404-4535078-5241919,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3645,JNE3645-TP-N-L,Top,...,INR,432.0,PUNE,MAHARASHTRA,411014.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
109,109,403-7266170-1163500,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3648,JNE3648-TP-N-M,Top,...,INR,518.0,MUMBAI,MAHARASHTRA,400076.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128923,128923,402-1698543-5164342,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0418,J0418-TP-XL,Top,...,INR,749.0,HYDERABAD,TELANGANA,500084.0,IN,"IN Core Free Shipping 2015/04/08 23-48-5-108,V...",False,NaN,False
128941,128941,403-3035549-4142738,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0118,J0118-TP-XXL,Top,...,INR,529.0,BENGALURU,KARNATAKA,560102.0,IN,NaN,False,NaN,False
128942,128942,403-3035549-4142738,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0301,J0301-TP-XXL,Top,...,INR,518.0,BENGALURU,KARNATAKA,560102.0,IN,NaN,False,NaN,False
128949,128949,403-7050981-8813953,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0113,J0113-TP-M,Top,...,INR,574.0,CHENNAI,TAMIL NADU,600021.0,IN,NaN,False,NaN,False
128965,128965,408-5154281-4593912,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,J0119,J0119-TP-XXXL,Top,...,INR,574.0,Prayagraj (ALLAHABAD),UTTAR PRADESH,211007.0,IN,NaN,False,NaN,False

In [16]:
gut['Category'].unique

<bound method Series.unique of 0                   Set
1                 kurta
2                 kurta
3         Western Dress
4                   Top
              ...
128970            kurta
128971              Set
128972    Western Dress
128973              Set
128974              Set
Name: Category, Length: 128975, dtype: str>

In [34]:
gut[gut['ship-state'].str.contains("GUJARAT",case = False,na =False)]

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
65,65,171-4137548-0481151,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3373,JNE3373-KR-XXL,kurta,...,NaN,NaN,Dahod,Gujarat,389151.0,IN,NaN,False,NaN,NaN
78,78,403-6190683-2687538,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3861,JNE3861-DR-XL,Western Dress,...,INR,791.0,HIMMATNAGAR,Gujarat,383001.0,IN,NaN,False,NaN,NaN
89,89,171-6833843-5473114,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3560,JNE3560-KR-M,kurta,...,INR,487.0,VADODARA,Gujarat,390019.0,IN,NaN,False,NaN,NaN
93,93,406-5727754-5302723,04-30-22,Shipped,Amazon,Amazon.in,Expedited,SET098,SET098-KR-PP-M,Set,...,INR,696.0,VADODARA,Gujarat,390018.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
94,94,405-0901744-8270705,04-30-22,Shipped,Amazon,Amazon.in,Expedited,MEN5013,MEN5013-KR-L,kurta,...,INR,499.0,VADODARA,Gujarat,390003.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128838,128838,402-3140751-2277925,06-01-22,Shipped,Amazon,Amazon.in,Expedited,MEN5004,MEN5004-KR-XXL,kurta,...,INR,709.0,Ahmedabad,Gujarat,380015.0,IN,NaN,False,NaN,False
128858,128858,403-3993144-2397937,06-01-22,Shipped,Amazon,Amazon.in,Expedited,SET300,SET300-KR-NP-M,Set,...,INR,967.0,AHMEDABAD,Gujarat,380015.0,IN,NaN,False,NaN,False
128935,128935,408-3874942-4863549,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0341,J0341-DR-XL,Western Dress,...,INR,885.0,AHMEDABAD,Gujarat,382345.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128961,128961,402-0082204-6323568,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3797,JNE3797-KR-A-XL,Western Dress,...,INR,771.0,Junagadh,Gujarat,362001.0,IN,NaN,False,NaN,False
128973,128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,...,INR,1199.0,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False

In [33]:
gut[(gut['ship-state']=="Gujarat")]

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
65,65,171-4137548-0481151,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3373,JNE3373-KR-XXL,kurta,...,NaN,NaN,Dahod,Gujarat,389151.0,IN,NaN,False,NaN,NaN
78,78,403-6190683-2687538,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3861,JNE3861-DR-XL,Western Dress,...,INR,791.0,HIMMATNAGAR,Gujarat,383001.0,IN,NaN,False,NaN,NaN
89,89,171-6833843-5473114,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3560,JNE3560-KR-M,kurta,...,INR,487.0,VADODARA,Gujarat,390019.0,IN,NaN,False,NaN,NaN
93,93,406-5727754-5302723,04-30-22,Shipped,Amazon,Amazon.in,Expedited,SET098,SET098-KR-PP-M,Set,...,INR,696.0,VADODARA,Gujarat,390018.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
94,94,405-0901744-8270705,04-30-22,Shipped,Amazon,Amazon.in,Expedited,MEN5013,MEN5013-KR-L,kurta,...,INR,499.0,VADODARA,Gujarat,390003.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128838,128838,402-3140751-2277925,06-01-22,Shipped,Amazon,Amazon.in,Expedited,MEN5004,MEN5004-KR-XXL,kurta,...,INR,709.0,Ahmedabad,Gujarat,380015.0,IN,NaN,False,NaN,False
128858,128858,403-3993144-2397937,06-01-22,Shipped,Amazon,Amazon.in,Expedited,SET300,SET300-KR-NP-M,Set,...,INR,967.0,AHMEDABAD,Gujarat,380015.0,IN,NaN,False,NaN,False
128935,128935,408-3874942-4863549,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0341,J0341-DR-XL,Western Dress,...,INR,885.0,AHMEDABAD,Gujarat,382345.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128961,128961,402-0082204-6323568,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3797,JNE3797-KR-A-XL,Western Dress,...,INR,771.0,Junagadh,Gujarat,362001.0,IN,NaN,False,NaN,False
128973,128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,...,INR,1199.0,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False

In [41]:
gut[gut['Order ID'].str.startswith(107)]

TypeError: expected a string or tuple, not int

In [40]:
gut[gut['Category'].str.startswith("Top")]

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.0,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN
47,47,408-9281152-6213100,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3744,JNE3744-TU-S,Top,...,INR,665.0,SECUNDERABAD,TELANGANA,500017.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
54,54,402-7944191-1869101,04-30-22,Shipped,Amazon,Amazon.in,Expedited,J0301,J0301-TP-L,Top,...,INR,493.0,BENGALURU,KARNATAKA,560076.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
67,67,404-4535078-5241919,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3645,JNE3645-TP-N-L,Top,...,INR,432.0,PUNE,MAHARASHTRA,411014.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
109,109,403-7266170-1163500,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3648,JNE3648-TP-N-M,Top,...,INR,518.0,MUMBAI,MAHARASHTRA,400076.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128923,128923,402-1698543-5164342,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0418,J0418-TP-XL,Top,...,INR,749.0,HYDERABAD,TELANGANA,500084.0,IN,"IN Core Free Shipping 2015/04/08 23-48-5-108,V...",False,NaN,False
128941,128941,403-3035549-4142738,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0118,J0118-TP-XXL,Top,...,INR,529.0,BENGALURU,KARNATAKA,560102.0,IN,NaN,False,NaN,False
128942,128942,403-3035549-4142738,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0301,J0301-TP-XXL,Top,...,INR,518.0,BENGALURU,KARNATAKA,560102.0,IN,NaN,False,NaN,False
128949,128949,403-7050981-8813953,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0113,J0113-TP-M,Top,...,INR,574.0,CHENNAI,TAMIL NADU,600021.0,IN,NaN,False,NaN,False
128965,128965,408-5154281-4593912,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,J0119,J0119-TP-XXXL,Top,...,INR,574.0,Prayagraj (ALLAHABAD),UTTAR PRADESH,211007.0,IN,NaN,False,NaN,False