In [19]:
import pandas as pd
import numpy as nb
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
df = pd.read_csv(r"C:\Users\aalgo\Downloads\archive_(4)\Amazon_Sale_Report.csv")

C:\Users\aalgo\AppData\Local\Temp\ipykernel_27056\742653858.py:1: DtypeWarning: Columns (0: Unnamed: 22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\aalgo\Downloads\archive_(4)\Amazon_Sale_Report.csv")

In [21]:
df.shape

(128975, 24)

In [22]:
df.set_index("index", inplace=True)

In [23]:
df.tail()

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
index,,,,,,,,,,,,,,,,,,,,,
128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,XL,...,INR,517.0,HYDERABAD,TELANGANA,500013.0,IN,NaN,False,NaN,False
128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,M,...,INR,999.0,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,XXL,...,INR,690.0,HYDERABAD,TELANGANA,500049.0,IN,NaN,False,NaN,False
128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,XS,...,INR,1199.0,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128974,408-7436540-8728312,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,S,...,INR,696.0,Raipur,CHHATTISGARH,492014.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False

In [24]:
df.describe()

                 Qty         Amount  ship-postal-code
count  128975.000000  121180.000000     128942.000000
mean        0.904431     648.561465     463966.236509
std         0.313354     281.211687     191476.764941
min         0.000000       0.000000     110001.000000
25%         1.000000     449.000000     382421.000000
50%         1.000000     605.000000     500033.000000
75%         1.000000     788.000000     600024.000000
max        15.000000    5584.000000     989898.000000

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 23 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order ID            128975 non-null  str
 1   Date                128975 non-null  str
 2   Status              128975 non-null  str
 3   Fulfilment          128975 non-null  str
 4   Sales Channel       128975 non-null  str
 5   ship-service-level  128975 non-null  str
 6   Style               128975 non-null  str
 7   SKU                 128975 non-null  str
 8   Category            128975 non-null  str
 9   Size                128975 non-null  str
 10  ASIN                128975 non-null  str
 11  Courier Status      122103 non-null  str
 12  Qty                 128975 non-null  int64
 13  currency            121180 non-null  str
 14  Amount              121180 non-null  float64
 15  ship-city           128942 non-null  str
 16  ship-state          128942 non-null  str
 17  ship-postal-code    128942 non-null  float64
 18  ship-country        128942 non-null  str
 19  promotion-ids       79822 non-null   str
 20  B2B                 128975 non-null  bool
 21  fulfilled-by        39277 non-null   str
 22  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(1), object(1), str(18)
memory usage: 21.8+ MB

**no need to do df.fillna or df.dropna here**

In [26]:
df.head()

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
index,,,,,,,,,,,,,,,,,,,,,
0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [27]:
df['ship-city'] = df['ship-city'].str.lower()

In [28]:
df['ship-city'] = df['ship-city'].str.upper()

In [29]:
df.loc[50]

Order ID                                       408-2137113-0982751
Date                                                      04-30-22
Status                                                     Shipped
Fulfilment                                                  Amazon
Sales Channel                                            Amazon.in
ship-service-level                                       Expedited
Style                                                        J0186
SKU                                                    J0186-SET-S
Category                                                       Set
Size                                                             S
ASIN                                                    B091Z81MLX
Courier Status                                             Shipped
Qty                                                              1
currency                                                       INR
Amount                                                       848.0
ship-city                                                  CUTTACK
ship-state                                                  ODISHA
ship-postal-code                                          753012.0
ship-country                                                    IN
promotion-ids         IN Core Free Shipping 2015/04/08 23-48-5-108
B2B                                                          False
fulfilled-by                                                   NaN
Unnamed: 22                                                    NaN
Name: 50, dtype: object

In [30]:
df

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
index,,,,,,,,,,,,,,,,,,,,,
0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,XL,...,INR,517.00,HYDERABAD,TELANGANA,500013.0,IN,NaN,False,NaN,False
128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,M,...,INR,999.00,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,XXL,...,INR,690.00,HYDERABAD,TELANGANA,500049.0,IN,NaN,False,NaN,False
128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,XS,...,INR,1199.00,HALOL,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128974,408-7436540-8728312,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,S,...,INR,696.00,RAIPUR,CHHATTISGARH,492014.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False

In [31]:
df

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
index,,,,,,,,,,,,,,,,,,,,,
0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,XL,...,INR,517.00,HYDERABAD,TELANGANA,500013.0,IN,NaN,False,NaN,False
128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,M,...,INR,999.00,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,XXL,...,INR,690.00,HYDERABAD,TELANGANA,500049.0,IN,NaN,False,NaN,False
128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,XS,...,INR,1199.00,HALOL,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128974,408-7436540-8728312,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,S,...,INR,696.00,RAIPUR,CHHATTISGARH,492014.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False

In [32]:
df.groupby('Category')['Amount'].sum()

Category
Blouse             458408.18
Bottom             150667.98
Dupatta               915.00
Ethnic Dress       791217.66
Saree              123933.76
Set              39204124.03
Top               5347792.30
Western Dress    11216072.69
kurta            21299546.70
Name: Amount, dtype: float64

In [49]:
df.sample(5)

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
index,,,,,,,,,,,,,,,,,,,,,
43827,403-0499978-2057911,04-04-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3797,JNE3797-KR-XXXL,Western Dress,3XL,...,INR,715.0,ERNAKULAM,KERALA,682038.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
98302,408-9484919-8929910,06-23-22,Shipped,Amazon,Amazon.in,Expedited,NW029,NW029-ST-SR-L,Set,L,...,INR,441.0,FARIDABAD,HARYANA,121004.0,IN,NaN,False,NaN,False
77897,406-8417798-5008349,05-08-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3652,JNE3652-TP-N-XL,Top,XL,...,INR,328.0,KOCHI,KERALA,682017.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,False
16617,406-9325563-2723527,04-20-22,Shipped,Amazon,Amazon.in,Expedited,BL021,BL021-71BLACK,Blouse,Free,...,INR,419.0,AHMEDABAD,Gujarat,380015.0,IN,NaN,False,NaN,NaN
66899,407-6650964-3555520,05-17-22,Shipped,Amazon,Amazon.in,Expedited,J0376,J0376-SKD-XXXL,Set,3XL,...,INR,1063.0,HYDERABAD,TELANGANA,500002.0,IN,NaN,False,NaN,False

In [54]:
df.at[3,"Amount"]

np.float64(753.33)

In [55]:
df.head(4)

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
index,,,,,,,,,,,,,,,,,,,,,
0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN

In [61]:
df.sort_values(["Amount","Category"],ascending=False)

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
index,,,,,,,,,,,,,,,,,,,,,
42039,402-5239558-4281957,04-05-22,Shipped,Amazon,Amazon.in,Expedited,SET268,SET268-KR-NP-XS,Set,XS,...,INR,5584.00,GUNTUR,ANDHRA PRADESH,522007.0,IN,NaN,False,NaN,NaN
11160,403-4106553-1691525,04-23-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,J0013,J0013-SKD-XXXL,Set,3XL,...,INR,5495.00,JALANDHAR,PUNJAB,144022.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,True,Easy Ship,NaN
24494,407-3483041-9133135,04-16-22,Cancelled,Merchant,Amazon.in,Standard,SET397,SET397-KR-NP -M,Set,M,...,INR,4235.72,JAIPUR,RAJASTHAN,302012.0,IN,NaN,False,Easy Ship,NaN
89150,406-7195963-2374765,05-02-22,Shipped,Amazon,Amazon.in,Expedited,SET197,SET197-KR-NP-M,Set,M,...,INR,3036.00,LUCKNOW,UTTAR PRADESH,226002.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
121225,404-4712917-7300332,06-06-22,Shipped,Amazon,Amazon.in,Expedited,SET278,SET278-KR-NP-XXXL,Set,3XL,...,INR,2894.00,MUMBAI,MAHARASHTRA,400081.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105300,406-4610317-1624353,06-17-22,Cancelled,Amazon,Amazon.in,Expedited,BL021,BL021-71BLACK,Blouse,Free,...,NaN,NaN,NEW DELHI,DELHI,110037.0,IN,NaN,False,NaN,False
107613,171-8009518-6065920,06-15-22,Cancelled,Amazon,Amazon.in,Expedited,BL006,BL006-54BLACK,Blouse,Free,...,NaN,NaN,HYDERABAD,TELANGANA,500084.0,IN,NaN,False,NaN,False
110030,405-7922418-6021961,06-13-22,Cancelled,Amazon,Amazon.in,Expedited,BL035,BL035-161GOLD,Blouse,Free,...,NaN,NaN,GURUGRAM,HARYANA,122001.0,IN,NaN,False,NaN,False
126738,407-6131601-8283520,06-02-22,Cancelled,Amazon,Amazon.in,Expedited,J0217,J0217-BL-M,Blouse,M,...,NaN,NaN,PATNA,BIHAR,800027.0,IN,NaN,False,NaN,False
127855,171-0571463-7446765,06-01-22,Cancelled,Amazon,Amazon.in,Expedited,J0220,J0220-BL-L,Blouse,L,...,NaN,NaN,BADDI,HIMACHAL PRADESH,173205.0,IN,NaN,False,NaN,False